project:
  type: website

website:
  title: "MP2023"
  navbar:
    right:
      - icon: github    
        href: https://github.com/guebin/MP2023
      - icon: youtube
        href: https://www.youtube.com/channel/UCQk9RyBNgXc7ORIsYlOfQrg/playlists?view=50&sort=dd&shelf_id=2
format:
  html:
    theme: cosmo
    css: styles.css


bibliography: ./posts/ref.bib

